USE [HospitalManagment]
GO

/****** Object:  Table [dbo].[IPD]    Script Date: 1/16/2018 10:11:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IPD](
	[IPDId] [int] IDENTITY(1,1) NOT NULL,
	[TypeOfRoomAndBedId] [int] NOT NULL,
	[AdmissionDate] [date] NULL,
 CONSTRAINT [PK_IPD] PRIMARY KEY CLUSTERED 
(
	[IPDId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[IPD]  WITH CHECK ADD  CONSTRAINT [FK_IPD_TypeOfRoomAndBed1] FOREIGN KEY([TypeOfRoomAndBedId])
REFERENCES [dbo].[TypeOfRoomAndBed] ([TypeOfRoomAndBedId])
GO

ALTER TABLE [dbo].[IPD] CHECK CONSTRAINT [FK_IPD_TypeOfRoomAndBed1]
GO


