//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.PersonDetails = new HashSet<PersonDetail>();
        }
    
        public int ContactId { get; set; }
        public string EmailId { get; set; }
        public string ContactNumber { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<PersonDetail> PersonDetails { get; set; }
    }
}
