//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConservativeDetail> ConservativeDetails { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Investigation> Investigations { get; set; }
        public virtual DbSet<IPD> IPDs { get; set; }
        public virtual DbSet<LabourDetail> LabourDetails { get; set; }
        public virtual DbSet<MedcineName> MedcineNames { get; set; }
        public virtual DbSet<MonitoringChart> MonitoringCharts { get; set; }
        public virtual DbSet<OPD> OPDs { get; set; }
        public virtual DbSet<OperationDetail> OperationDetails { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonDetail> PersonDetails { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<TreatmentChart> TreatmentCharts { get; set; }
        public virtual DbSet<TypeofCheckUp> TypeofCheckUps { get; set; }
        public virtual DbSet<TypeOfIntakeAdv> TypeOfIntakeAdvs { get; set; }
        public virtual DbSet<TypeOfMedcine> TypeOfMedcines { get; set; }
        public virtual DbSet<TypeOfOperation> TypeOfOperations { get; set; }
        public virtual DbSet<TypeOfRoomAndBed> TypeOfRoomAndBeds { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
