//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigation
    {
        public int InvestigationId { get; set; }
        public int OpdId { get; set; }
        public string BloodGroup { get; set; }
        public string HB { get; set; }
        public string RBS { get; set; }
        public string HIV_II { get; set; }
        public string HBSAvg { get; set; }
        public string VDRL { get; set; }
        public string UrineRM { get; set; }
        public string Sr_Creat { get; set; }
        public string Sr_Urea { get; set; }
        public string Sr_TSH { get; set; }
        public string HSG { get; set; }
        public string SemenAnalysis { get; set; }
        public string USG { get; set; }
        public string Other { get; set; }
        public byte[] AllAttachmentinOnePDF { get; set; }
    
        public virtual OPD OPD { get; set; }
    }
}
