//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPD()
        {
            this.ConservativeDetails = new HashSet<ConservativeDetail>();
            this.LabourDetails = new HashSet<LabourDetail>();
            this.OperationDetails = new HashSet<OperationDetail>();
        }
    
        public int IPDId { get; set; }
		public string IpdNumber { get; set; }
        public int TypeOfRoomAndBedId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConservativeDetail> ConservativeDetails { get; set; }
        public virtual TypeOfRoomAndBed TypeOfRoomAndBed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabourDetail> LabourDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationDetail> OperationDetails { get; set; }
    }
}
