//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedcineName
    {
        public MedcineName()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int MedcineNamesId { get; set; }
        public string MedcineName1 { get; set; }
        public Nullable<decimal> MedicineWeight { get; set; }
        public int TypeOfMedicineId { get; set; }
    
        public virtual TypeOfMedcine TypeOfMedcine { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
