//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitoringChart
    {
        public int MonitoringChartId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string BP { get; set; }
        public Nullable<int> Pulse { get; set; }
        public string RsNCVS { get; set; }
        public string PA { get; set; }
        public string PV { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
    }
}
