//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPD
    {
        public OPD()
        {
            this.Investigations = new HashSet<Investigation>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int OPDId { get; set; }
        public int PersonID { get; set; }
        public int TypeofCheckUp { get; set; }
        public Nullable<System.DateTime> NextAppoinmentDate { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public decimal Weight { get; set; }
        public string BP { get; set; }
        public Nullable<int> Pulse { get; set; }
        public string OPDNumber { get; set; }
        public string Rs { get; set; }
        public string PA { get; set; }
        public string PS { get; set; }
        public string PV { get; set; }
        public string CNS { get; set; }
        public Nullable<System.DateTime> OPDDate { get; set; }
        public string CVS { get; set; }
        public string BMI { get; set; }
        public string OtherGeneralFindings { get; set; }
    
        public virtual ICollection<Investigation> Investigations { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual Person Person { get; set; }
        public virtual TypeofCheckUp TypeofCheckUp1 { get; set; }
    }
}
