//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentDetailsID { get; set; }
        public decimal ConsultingFee { get; set; }
        public decimal DeliveryFee { get; set; }
        public decimal RoomChargesPerDay { get; set; }
        public decimal VaccineFee { get; set; }
        public decimal ECGFee { get; set; }
        public decimal MedicineCost { get; set; }
        public decimal MedicalTest { get; set; }
    }
}
