//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonType
    {
        public PersonType()
        {
            this.PersonDetails = new HashSet<PersonDetail>();
        }
    
        public int PersonTypeId { get; set; }
        public string NameOfType { get; set; }
    
        public virtual ICollection<PersonDetail> PersonDetails { get; set; }
    }
}
