//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDetail
    {
        public int PersonDetailsId { get; set; }
        public int ContactID { get; set; }
        public int PersonTypeID { get; set; }
        public int PersonID { get; set; }
        public int SpouseID { get; set; }
        public string ChildIDs { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual PersonType PersonType { get; set; }
    }
}
