//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeofCheckUp
    {
        public TypeofCheckUp()
        {
            this.OPDs = new HashSet<OPD>();
        }
    
        public int TypeofCheckUpId { get; set; }
        public string CheckupName { get; set; }
    
        public virtual ICollection<OPD> OPDs { get; set; }
    }
}
